version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/apps/*"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: "npm"
    directory: "/packages/*"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(deps)"
