import type { Metadata } from 'next'
import './globals.css'
import { PropsWithChildren } from 'react'
import { ApolloWrapper } from '../context/ApolloWrapper'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout: React.FC<Readonly<PropsWithChildren>> = ({ children }) => {
  return (
    <html lang={'en'}>
      <body>
        <ApolloWrapper>{children}</ApolloWrapper>
      </body>
    </html>
  )
}

export default RootLayout
