import type { Metadata } from 'next'
import './globals.css'
import React, { PropsWithChildren } from 'react'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout: React.FC<PropsWithChildren> = ({ children }) => {
  return (
    <html lang={'en'}>
      <body>{children}</body>
    </html>
  )
}

export default RootLayout
