name: Bump Dependencies

on:
  schedule:
    - cron: '0 9 * * 3'
  workflow_dispatch:
    inputs:
      base_branch:
        description: 'Base branch for the pull request'
        required: true
        default: 'main'

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Bun
        run: |
          curl https://bun.sh/install | bash
          export BUN_INSTALL="$HOME/.bun"
          export PATH="$BUN_INSTALL/bin:$PATH"
          echo "$BUN_INSTALL/bin" >> $GITHUB_PATH
          bun --version
      - name: Run Bun bump
        run: |
          bun bump

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b chore/bump || git checkout chore/bump
          git add .
          git commit -m "bump"
          git push origin chore/bump

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: chore/bump
          title: "bump dependencies"
          body: "This PR updates all dependencies."
          labels: "dependencies"
          base: main
