name: Lint and Test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      db_name:
        default: 'db_name'
      db_password:
        default: 'db_password'
jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:16.1
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ github.event.inputs.db_password }}
          POSTGRES_DB: ${{ github.event.inputs.db_name }}
        options: --health-cmd "pg_isready -U postgres" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Bun
        run: |
          curl https://bun.sh/install | bash
          export BUN_INSTALL="$HOME/.bun"
          export PATH="$BUN_INSTALL/bin:$PATH"
          echo "$BUN_INSTALL/bin" >> $GITHUB_PATH
          bun --version

      - name: Extract Node.js version from package.json
        id: node-version
        run: echo "NODE_VERSION=$(jq -r .engines.node package.json)" >> $GITHUB_ENV

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: bun i

      - name: Run linter
        run: bun biome:format && bun run lint

      - name: Run tests
        env:
          DATABASE_URL: 'postgresql://postgres:db_password@localhost:5432/postgres?schema=public'
        run: bun run test
